// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'fir-73517',
    appId: '1:119690914028:web:f6ea1100d6ae3f25865dc9',
    databaseURL: 'https://fir-73517.firebaseio.com',
    storageBucket: 'fir-73517.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyDdzXz1NtOTBHrtkeaFLAk71FH_rkf-93M',
    authDomain: 'fir-73517.firebaseapp.com',
    messagingSenderId: '119690914028',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['es-ES'],
};
